### ISSUE TITLE
Desenvolver os validadores de entrada

### ISSUE THREAD

**Issue by Marcosccp04** [Marcosccp04/sobre-github-workflow#1]
Esta issue tem como objetivo geral implementar validadores para diferentes tipos de dados em um projeto. O objetivo é criar funções que validem diferentes tipos de dados de acordo com as normas estabelecidas, como telefone, e-mail, CEP e CPF. As funções devem ser capazes de verificar se os dados fornecidos são válidos e retornar um valor booleano indicando se são válidos ou não. Além disso, as funções devem ser testadas para garantir que funcionem corretamente em diferentes cenários.

Para implementar os validadores, serão criadas issues específicas para cada tipo de validação, que deverão ser referenciadas nesta issue. Além disso, serão definidos milestones específicos para cada validação, que permitirão acompanhar o progresso do trabalho e identificar possíveis problemas.

#2 
#3 
#4 
#5

**Comment by maike616** [comment]
> Esta issue tem como objetivo geral implementar validadores para diferentes tipos de dados em um projeto. O objetivo é criar funções que validem diferentes tipos de dados de acordo com as normas estabelecidas, como telefone, e-mail, CEP e CPF. As funções devem ser capazes de verificar se os dados fornecidos são válidos e retornar um valor booleano indicando se são válidos ou não. Além disso, as funções devem ser testadas para garantir que funcionem corretamente em diferentes cenários.
> 
> Para implementar os validadores, serão criadas issues específicas para cada tipo de validação, que deverão ser referenciadas nesta issue. Além disso, serão definidos milestones específicos para cada validação, que permitirão acompanhar o progresso do trabalho e identificar possíveis problemas.
> 
> #2 #3 #4 #5
